### PR TITLE
Added robots meta tag if in development

### PR DESCRIPTION
**Pull request by Kourchenko**

### CODE REVIEW

**Comment by noahbrenner** [comment]
Just to make sure, is this code evaluated server-side? If the tag is added client-side, most search engines won't see it, since they don't parse JS (I'm not sure if even Google will respond to dynamic meta tags).

**Comment by noahbrenner** [comment]
I'm actually thinking that we should have a different approach to this. Our plan for the new frontend is to use [Pug](https://pugjs.org/api/getting-started.html) for templates, so we'll want to be writing `.pug` files instead of `.html` files anyway.

Whether we render templates at build time or at the server's runtime, using templates will allow us to conditionally add the meta tags based on environment variables, which I think is a better solution than adding them dynamically on the client side. That approach, however, would mean that implementing #20 should wait until after we have the boilerplate Pug views and the logic for rendering them implemented (it also means deciding whether to render at build time or at run time).

**Comment by Kourchenko** [comment]
> 
> 
> I'm actually thinking that we should have a different approach to this. Our plan for the new frontend is to use [Pug](https://pugjs.org/api/getting-started.html) for templates, so we'll want to be writing `.pug` files instead of `.html` files anyway.
> 
> Whether we render templates at build time or at the server's runtime, using templates will allow us to conditionally add the meta tags based on environment variables, which I think is a better solution than adding them dynamically on the client side. That approach, however, would mean that implementing #20 should wait until after we have the boilerplate Pug views and the logic for rendering them implemented (it also means deciding whether to render at build time or at run time).

 This is a really good point. Since the plan was to render HTML files server-side, the HTML file would be rendered, the meta tag added during render, and then the HTML file would be sent (with/without meta tag). But if we're using a templating engine, we can generate HTML depending on server environment variables, which we're not able to retrieve client-side.

**Comment by noahbrenner** [comment]
For that matter, since we're writing a server (not just serving static files from Nginx, etc.) We could use a robots.txt file instead of a meta tag and conditionally choose which version of robots.txt to serve. That keeps the configuration in one place and then there's no need to add any markup at all.

**Pull request closed without merging**
