### PR TITLE
Initial project files

### PR DESCRIPTION
**Pull request by ryanrolds**
This sets up project with:
* Node 12.4.0
* TypeScript
* eslint
* Circle CI
* And watching functionality that will rebuild and restart the app

### CODE REVIEW

**Comment by noahbrenner** [comment]
What do you think of including `tsc -p . --noEmit` in the npm lint task? Or is everything it would do covered by eslint or our build process that isn't defined there yet? Since we're requiring linting and tests to pass for PRs, that seems like something we should cover.

**Comment by ryanrolds** [comment]
Good catch. I removed lint from the `start-dev` script.

**Comment by ryanrolds** [comment]
I would like to keep the tsc output. As we will want output from the watcher related builds.

**Comment by noahbrenner** [comment]
Oh, glad you caught that! I was actually thinking of something else:

* Circle CI runs `lint` and `test`, which must pass for PRs to be merged.
* Right now, `lint` only includes calling `eslint`, not type checking with `tsc`.
* The `test` task is currently empty.
* This means that Circle CI won't be checking typings with `tsc` when deciding if a PR can be merged. That's why I was suggesting *adding* `tsc` to the `lint` task.

On a side note, `npm` adds `node_modules/.bin` to the path when executing npm scripts, so we can probably just define `"lint": "eslint *.json src/**/*.ts"`.

**Comment by ryanrolds** [comment]
Good gatch. CI now runs build, which will run tsc.

**Comment by noahbrenner** [comment]
Great! A couple last questions for you:

1. Is there a good reason for specifying the full `./node_modules/.bin/...` path in `npm run lint` rather than making use of npm [adding that directory to the path](https://docs.npmjs.com/cli/run-script.html)?
2. I noticed that a bunch of these files don't have newline character on the last line. Is there a reason for that? I think we're requiring trailing newlines in our linting rules, so it might make sense to be consistent with that for all files.

**Comment by ryanrolds** [comment]
Specifying the relative path is a habit. Sometimes Windows devs are on a project and Windows doesn't have symlinks. I don't know if that has changed or if node.js added a workaround. I will remove it. I will also add those new lines.

**Comment by noahbrenner** [comment]
Sounds good, just wanted to check! For the record, I used Windows 7 for a long time and didn't have issues with npm scripts. It still makes sure the files in the `.bin` directory are executable and have an extension that doesn't have to be specified on the Windows command line.

**Comment by noahbrenner** [comment]
Just in the Circle CI config, would we want to run [`npm ci`](https://docs.npmjs.com/cli/ci.html#description) rather than `npm install` so that we're installing exactly what's defined in `package.json` before building/testing?

**Comment by noahbrenner** [comment]
After your fix for mounting `node_modules`, the server now starts successfully and a `node_modules` directory is created in my local project directory!

**Next issue:** The node_modules directory in my local project directory exists, but is empty. This prevents me from running `npm test` or `npm run lint` directly. This issue persisted after running `docker-compose up --build frontend-v2`. It seems that the Docker image now has a populated node_modules directory, but the project working directory does not. I'm running Ubuntu 18.04.2 LTS.

**Comment by noahbrenner** [comment]
One workaround would be to run `npm ci` or `npm install` again locally, though I don't know if shadowing node_modules is the best option.

**Comment by ryanrolds** [comment]
You have to run it in the container.

**Comment by noahbrenner** [comment]
I'm in favor of strict type checking. What do you think of adding these to `compilerOptions` in `tsconfig.json`?

```json
// We probably want this
"strict": true,

// These are other potentially good things, though maybe
// they're not necessary since they're more the job of eslint
"noFallthroughCasesInSwitch": true,
"noImplicitReturns": true,
"noUnusedLocals": true,
"noUnusedParameters": true,
```

**Comment by ryanrolds** [comment]
I will add them when I get home.

**Pull request merged**
